[package]
name = "overline-protocol"
version = "0.1.0"
authors = ["Adam Kloboucnik <adam@klob.cz>"]
edition = "2018"
license = "MIT"

[dependencies]
base16 = { version = "0.2.1", default-features = false }
cobs = { version = "0.1.4", default-features = false }
heapless = "0.6.1"
rand = { version = "0.7.3", default-features = false, features = ["small_rng"]}
typenum = "1.13.0"

[dev-dependencies]
rand = { version = "0.7.3"}

[features]
debug = []
