name: Notify Telegram
on:
  push:
  release:
    types: [published]

jobs:
  notify:
    name: Notify via Telegram
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Telegram
        uses: Lukasss93/telegram-action@v2
        env:
          TELEGRAM_TOKEN: ${{ secrets.BC_DEV_BOT_TOKEN }}
          TELEGRAM_CHAT: ${{ secrets.BC_CORE_CHAT_ID }}
